version: "3.8"
services:
  db:
    image: mariadb:10.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: order-service
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev




